-- Run this once in Supabase SQL Editor
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null unique,
  author text not null,
  category text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.reload_schema_cache()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform pg_notify('pgrst', 'reload schema');
end;
$$;

grant execute on function public.reload_schema_cache() to authenticated;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.books to authenticated;

create table if not exists public.borrow_requests (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id text not null,
  book_name text,
  author text,
  status text not null default 'Pending',
  request_date timestamptz not null default now(),
  due_date timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  returned_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint borrow_requests_status_check check (status in ('Pending', 'Approved', 'Rejected', 'Returned', 'Cancelled'))
);

grant select, insert, update, delete on public.borrow_requests to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
    'student'
  )
  on conflict (user_id)
  do update set
    full_name = excluded.full_name,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at
before update on public.profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists touch_borrow_requests_updated_at on public.borrow_requests;
create trigger touch_borrow_requests_updated_at
before update on public.borrow_requests
for each row
execute function public.touch_updated_at();

drop trigger if exists touch_books_updated_at on public.books;
create trigger touch_books_updated_at
before update on public.books
for each row
execute function public.touch_updated_at();

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'admin'
  )
  or lower(coalesce(auth.jwt() ->> 'email', '')) = 'cit.library@cit.edu';
$$;

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.borrow_requests enable row level security;

drop policy if exists "profiles_read_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_admin_all" on public.profiles;

create policy "profiles_read_own"
on public.profiles
for select
using (auth.uid() = user_id or public.current_user_is_admin());

create policy "profiles_insert_own"
on public.profiles
for insert
with check (auth.uid() = user_id or public.current_user_is_admin());

create policy "profiles_update_own"
on public.profiles
for update
using (auth.uid() = user_id or public.current_user_is_admin())
with check (auth.uid() = user_id or public.current_user_is_admin());

drop policy if exists "borrow_requests_read_own" on public.borrow_requests;
drop policy if exists "borrow_requests_insert_own" on public.borrow_requests;
drop policy if exists "borrow_requests_update_own" on public.borrow_requests;
drop policy if exists "borrow_requests_admin_all" on public.borrow_requests;

drop policy if exists "books_read_authenticated" on public.books;
drop policy if exists "books_admin_all" on public.books;

create policy "books_read_authenticated"
on public.books
for select
using (auth.role() = 'authenticated' or public.current_user_is_admin());

create policy "books_admin_all"
on public.books
for all
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

drop policy if exists "books_update_admin" on public.books;
drop policy if exists "books_delete_admin" on public.books;

create policy "borrow_requests_read_own"
on public.borrow_requests
for select
using (auth.uid() = user_id or public.current_user_is_admin());

create policy "borrow_requests_insert_own"
on public.borrow_requests
for insert
with check (auth.uid() = user_id);

create policy "borrow_requests_update_own"
on public.borrow_requests
for update
using (auth.uid() = user_id or public.current_user_is_admin())
with check (auth.uid() = user_id or public.current_user_is_admin());

-- Seed the ReadEase system administrator profile if the account already exists.
insert into public.profiles (user_id, full_name, role)
select id, 'Librarian Admin', 'admin'
from auth.users
where email = 'cit.library@cit.edu'
on conflict (user_id)
do update set
  full_name = excluded.full_name,
  role = excluded.role,
  updated_at = now();
