-- Minimal hotfix for the ReadEase admin book flow.
-- Run this in Supabase SQL Editor if the full bootstrap script did not finish.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null unique,
  author text not null,
  category text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.borrow_requests (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id text not null,
  book_name text,
  author text,
  status text not null default 'Pending',
  request_date timestamptz not null default now(),
  due_date timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  returned_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint borrow_requests_status_check check (status in ('Pending', 'Approved', 'Rejected', 'Returned', 'Cancelled'))
);

create or replace function public.reload_schema_cache()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform pg_notify('pgrst', 'reload schema');
end;
$$;

grant usage on schema public to authenticated;
grant execute on function public.reload_schema_cache() to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.books to authenticated;
grant select, insert, update, delete on public.borrow_requests to authenticated;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = auth.uid()
      and role = 'admin'
  )
  or lower(coalesce(auth.jwt() ->> 'email', '')) = 'cit.library@cit.edu';
$$;

create or replace function public.admin_get_all_borrow_requests()
returns setof public.borrow_requests
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Not authorized';
  end if;

  return query
    select *
    from public.borrow_requests
    order by request_date desc;
end;
$$;

grant execute on function public.admin_get_all_borrow_requests() to authenticated;

alter table public.profiles enable row level security;
alter table public.books enable row level security;
alter table public.borrow_requests enable row level security;

drop policy if exists "books_read_authenticated" on public.books;
drop policy if exists "books_admin_all" on public.books;
drop policy if exists "borrow_requests_read_own" on public.borrow_requests;
drop policy if exists "borrow_requests_insert_own" on public.borrow_requests;
drop policy if exists "borrow_requests_update_own" on public.borrow_requests;

create policy "books_read_authenticated"
on public.books
for select
using (auth.role() = 'authenticated' or public.current_user_is_admin());

create policy "books_admin_all"
on public.books
for all
using (public.current_user_is_admin())
with check (public.current_user_is_admin());

create policy "borrow_requests_read_own"
on public.borrow_requests
for select
using (auth.uid() = user_id or public.current_user_is_admin());

create policy "borrow_requests_insert_own"
on public.borrow_requests
for insert
with check (auth.uid() = user_id);

create policy "borrow_requests_update_own"
on public.borrow_requests
for update
using (auth.uid() = user_id or public.current_user_is_admin())
with check (auth.uid() = user_id or public.current_user_is_admin());

select public.reload_schema_cache();

-- Ensure the ReadEase system administrator profile is set up correctly
insert into public.profiles (user_id, full_name, role)
select id, 'Librarian Admin', 'admin'
from auth.users
where email = 'cit.library@cit.edu'
on conflict (user_id)
do update set
  full_name = excluded.full_name,
  role = excluded.role,
  updated_at = now();

-- Remove books added through Book Approval (keep only admin-created books)
delete from public.books where title in (
  'Atomic Habits',
  'Avengers',
  'Clean Code',
  'Educated',
  'Lord of the Rings',
  'One Piece',
  'Sapiens',
  'The Alchemist',
  'The Psychology of Money',
  'Titanic'
);